### ISSUE TITLE
Android Architecture ViewModel 

### ISSUE THREAD

**Issue by PabloRosas17** [PabloRosas17/MarvelDroid#1]
Issue will rework current architecture using observer observable pattern to use android architecture to use industry standard approach.

- [ ] Android [Architecture Components ViewModel official documentation](https://developer.android.com/topic/libraries/architecture/viewmodel)

**Comment by suekdroid** [comment]
Hello guys

**Comment by PabloRosas17** [comment]
check off on 02/09 meeting.
