### ISSUE TITLE
ComicBookFinderActivity, RecyclerView Toggler

### ISSUE THREAD

**Issue by PabloRosas17** [PabloRosas17/MarvelDroid#14]
User should be able to toggle between different recycler view settings, for instance, button 1 should display a list of comics with one card per row and many cards per column, button 2 should display a list of comics with two cards per row and many cards per column, button 3 should display a list of comics with three cards per row and many cards per column. ideally we can implement this with a GridView and a GridViewAdapter using the ViewHolder pattern, 

[android material design guidelines for gridview](https://material.io/design/layout/responsive-layout-grid.html#)

- [ ] toggler button

**Comment by gsttarun** [comment]
We should use recycler view with GridLayoutManager.
