### ISSUE TITLE
User Interface Design

### ISSUE THREAD

**Issue by PabloRosas17** [PabloRosas17/MarvelDroid#3]
Issue will be used as a chain to keep track of "mockups" for user interface on activities before beginning implementation.

- [ ] Login Activity.
- [ ] User Account Activity.
- [ ] Comic Book Finder Activity.
- [ ] Character Selector Drawer.
- [ ] Amazon Checkout.

**Comment by suekdroid** [comment]
Fragments?

**Comment by PabloRosas17** [comment]
> Fragments?

Is there use cases you can provide to think about this? Only if it makes sense to use them. Fragments are essentially "a portion of an activity sitting on top of other it" as stated by [fragments official documentation by android](https://developer.android.com/guide/components/fragments)

**Comment by PabloRosas17** [comment]
I've made design implementations for the UI following material design strict guidelines as well as meeting the requirements gathered from within the issues. Please provide feedback.

![Android Mobile – 1](https://user-images.githubusercontent.com/51768134/73607469-2141d080-456b-11ea-9d01-bf008c339cec.png)

![Android Mobile – 2](https://user-images.githubusercontent.com/51768134/73607471-256dee00-456b-11ea-9584-4716494d96ef.png)

![Android Mobile – 4](https://user-images.githubusercontent.com/51768134/73607473-2c94fc00-456b-11ea-959d-314547c26725.png)

![Android Mobile – 3](https://user-images.githubusercontent.com/51768134/73607474-2f8fec80-456b-11ea-9068-139c5a136db6.png)

![Android Mobile – 5](https://user-images.githubusercontent.com/51768134/73607475-31f24680-456b-11ea-829b-e85b85de47b6.png)

![Android Mobile – 6](https://user-images.githubusercontent.com/51768134/73607477-3454a080-456b-11ea-8fae-4b136c5cad49.png)

![Android Mobile – 7](https://user-images.githubusercontent.com/51768134/73607479-361e6400-456b-11ea-8cf0-747772cac771.png)

**Comment by PabloRosas17** [comment]
Please note I have the assets and design for this UI as of 02/02/2020, we will upload them to the repository soon in the future.
