### ISSUE TITLE
API Libraries Definitions

### ISSUE THREAD

**Issue by PabloRosas17** [PabloRosas17/MarvelDroid#5]
Issue will keep track of api's, libraries, and any other technology that would be suitable for the project, ideally add a description as well.

- [x] Retrofit , [Retrofit](https://square.github.io/retrofit/) , for the purpose of http client.
- [x] Koin , [Koin](https://insert-koin.io/) , for the purpose of dependency injection.
- [x] Marvel , [Marvel](https://developer.marvel.com/) , for the api data source.

**Comment by gsttarun** [comment]
Logging - timber
OnDevice Crash Notifications and HTTP requests viewing - Chucker

**Comment by PabloRosas17** [comment]
I do believe I fell in love with this, what do you think for permissions api? 
[Dexter](https://github.com/karumi/dexter)

**Comment by PabloRosas17** [comment]
> Logging - [timber](https://github.com/JakeWharton/timber)
> OnDevice Crash Notifications and HTTP requests viewing - [Chucker](https://github.com/ChuckerTeam/chucker)

Timber - this seems like a good library for larger scale projects, considering the size of this one i'd advise we defer from using this as i do believe it will cause more overhead than anything else.

Chucker - this seems okay as well, but since we're moving towards the retrofit direction, again i appreciate the input but we should defer from using it for similar reasons as mentioned above.

**Comment by gsttarun** [comment]
> I do believe I fell in love with this, what do you think for permissions api? - [Dexter](https://github.com/karumi/dexter)

I will add that library. So what all permissions do we need ?

**Comment by PabloRosas17** [comment]
closed on after the meeting on 02/09.
