### ISSUE TITLE
LoginActivity, Login and Singup

### ISSUE THREAD

**Issue by suekdroid** [PabloRosas17/MarvelDroid#6]
User will have an elegant UI as the "TOP - very first screen" that the user will see.
They'll be presented with an option to create a username, a password, a login button, a sign up button, and an alternative to display "or login with facebook, or google". 

- [x] field for username
- [x] field for password
- [x] field for login
- [x]  field for sign up
- [ ] facebook button integration [login integration official documentation](https://developers.facebook.com/docs/facebook-login/android/)
- [ ] google button integration [login integration official documentation](https://developers.google.com/identity/sign-in/android/start-integrating)

**Comment by PabloRosas17** [comment]
Please provide some feedback on this simple login user interface i've created.
It follows all of material design guidelines.

<img width="209" alt="MarvelLoginActivity-Annotation 2020-02-02 013741" src="https://user-images.githubusercontent.com/51768134/73606181-a5408c00-455c-11ea-8ec4-67d1eb486333.png">

**Comment by suekdroid** [comment]
I'll begin looking at the signIn activity, i'll place it under core

**Comment by jeffbit** [comment]
I think this looks good. Do you think we should underline "terms of service" and on text click have it open a dialog fragment that shows the full terms and conditions.

**Comment by PabloRosas17** [comment]
> I think this looks good. Do you think we should underline "terms of service" and on text click have it open a dialog fragment that shows the full terms and conditions.

it's personal preference, but imo i believe we should bold it.
